In [65]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Asus\OneDrive\Desktop\Mini Project\GST Analysis\data\raw\customers.csv"
)

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    60 non-null     str
 1   customer_name  60 non-null     str
 2   state          60 non-null     str
 3   segment        60 non-null     str
 4   credit_days    60 non-null     int64
 5   gstin          55 non-null     str
dtypes: int64(1), str(5)
memory usage: 2.9 KB

In [67]:
df.describe()

       credit_days
count     60.00000
mean      29.00000
std       12.91432
min       15.00000
25%       15.00000
50%       30.00000
75%       45.00000
max       45.00000

In [68]:
df.isna().sum()

customer_id      0
customer_name    0
state            0
segment          0
credit_days      0
gstin            5
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
df[df['gstin'].isna()]

,customer_id,customer_name,state,segment,credit_days,gstin
4,C005,Trident Traders,Telangana,Retail,15,NaN
25,C026,Bharat Retail,Karnataka,Retail,15,NaN
38,C039,Jai Ganesh Distributors,Karnataka,Wholesale,30,NaN
53,C054,Unity Traders,Telangana,Wholesale,30,NaN
58,C059,Trident Enterprises,Maharashtra,Wholesale,30,NaN

In [71]:
df[df['gstin'].isna()][['customer_id', 'customer_name']]

   customer_id            customer_name
4         C005          Trident Traders
25        C026            Bharat Retail
38        C039  Jai Ganesh Distributors
53        C054            Unity Traders
58        C059      Trident Enterprises

In [72]:
sales_df = pd.read_csv("../data/raw/sales_invoices.csv")

In [73]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3633 entries, 0 to 3632
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   invoice_no     3633 non-null   str
 1   doc_type       3633 non-null   str
 2   invoice_date   3633 non-null   str
 3   customer_id    3633 non-null   str
 4   product_id     3633 non-null   str
 5   quantity       3633 non-null   int64
 6   unit_price     3633 non-null   int64
 7   discount_pct   3633 non-null   float64
 8   taxable_value  3633 non-null   float64
 9   cgst           3633 non-null   float64
 10  sgst           3633 non-null   float64
 11  igst           3633 non-null   float64
 12  payment_date   2971 non-null   str
 13  total_amount   3633 non-null   float64
dtypes: float64(6), int64(2), str(6)
memory usage: 397.5 KB

In [74]:
sales_df[['invoice_date', 'payment_date']].head(10)

  invoice_date payment_date
0  01-Apr-2025   2025-06-13
1   2025-04-01   2025-06-13
2   2025-04-01   2025-06-13
3   2025-04-01   23/05/2025
4   2025-04-01   2025-05-23
5   2025-04-01   2025-04-18
6   2025-04-01   2025-04-18
7  01-Apr-2025   2025-04-18
8   01/04/2025  28-Apr-2025
9   2025-04-01   2025-04-28

In [75]:
sales_df['invoice_date'] = pd.to_datetime(sales_df['invoice_date'], format='mixed')
sales_df['payment_date'] = pd.to_datetime(sales_df['payment_date'], format='mixed')

In [76]:
sales_df[["invoice_date", "payment_date"]].dtypes

invoice_date    datetime64[us]
payment_date    datetime64[us]
dtype: object

In [77]:
sales_df[["invoice_date", "payment_date"]].head(10)

  invoice_date payment_date
0   2025-04-01   2025-06-13
1   2025-04-01   2025-06-13
2   2025-04-01   2025-06-13
3   2025-04-01   2025-05-23
4   2025-04-01   2025-05-23
5   2025-04-01   2025-04-18
6   2025-04-01   2025-04-18
7   2025-04-01   2025-04-18
8   2025-01-04   2025-04-28
9   2025-04-01   2025-04-28

In [78]:
sales_df[sales_df["invoice_date"].dt.month == 1][["invoice_date"]].head(20)

     invoice_date
8      2025-01-04
12     2025-01-04
287    2025-01-05
290    2025-01-05
624    2025-01-06
1232   2025-01-08
1563   2025-01-09
1567   2025-01-09
1871   2025-01-10
2182   2025-01-11
2704   2026-01-01
2705   2026-01-01
2706   2026-01-01
2707   2026-01-01
2708   2026-01-01
2709   2026-01-01
2710   2026-01-01
2711   2026-01-01
2712   2026-01-01
2713   2026-01-01

In [79]:
sales_df = pd.read_csv("../data/raw/sales_invoices.csv")

In [80]:
sales_df["invoice_date"] = sales_df["invoice_date"].apply(
    lambda x: pd.to_datetime(x, format="%d/%m/%Y")
    if "/" in str(x)
    else pd.to_datetime(x, format="mixed")
)

sales_df["payment_date"] = sales_df["payment_date"].apply(
    lambda x: pd.to_datetime(x, format="%d/%m/%Y")
    if "/" in str(x)
    else pd.to_datetime(x, format="mixed")
)

In [81]:
sales_df[["invoice_date", "payment_date"]].head(10)

  invoice_date payment_date
0   2025-04-01   2025-06-13
1   2025-04-01   2025-06-13
2   2025-04-01   2025-06-13
3   2025-04-01   2025-05-23
4   2025-04-01   2025-05-23
5   2025-04-01   2025-04-18
6   2025-04-01   2025-04-18
7   2025-04-01   2025-04-18
8   2025-04-01   2025-04-28
9   2025-04-01   2025-04-28

In [82]:
sales_df[["invoice_date", "payment_date"]].dtypes

invoice_date    datetime64[us]
payment_date    datetime64[us]
dtype: object

In [83]:
sales_df.isna().sum()

invoice_no         0
doc_type           0
invoice_date       0
customer_id        0
product_id         0
quantity           0
unit_price         0
discount_pct       0
taxable_value      0
cgst               0
sgst               0
igst               0
payment_date     662
total_amount       0
dtype: int64

In [84]:
sales_df[sales_df['payment_date'].isna()] [['invoice_no', 'invoice_date', 'customer_id', 'total_amount']].head(20)

         invoice_no invoice_date customer_id  total_amount
21   INV-2526-00011   2025-04-02        C017       4198.32
22   INV-2526-00011   2025-04-02        C017      38232.00
23   INV-2526-00011   2025-04-02        C017     172800.00
32   INV-2526-00018   2025-04-03        C010       2478.00
33   INV-2526-00018   2025-04-03        C010     190668.80
55   INV-2526-00031   2025-04-07        C040      10201.10
56   INV-2526-00031   2025-04-07        C040      89208.00
89   INV-2526-00046   2025-04-10        C024      -3192.00
90   INV-2526-00046   2025-04-10        C024      -3192.00
93   INV-2526-00048   2025-04-10        C046     -14573.00
121  INV-2526-00060   2025-04-13        C020      88500.00
124  INV-2526-00062   2025-04-14        C001       1572.48
125  INV-2526-00062   2025-04-14        C001      84075.00
126  INV-2526-00062   2025-04-14        C001      15611.40
154  INV-2526-00076   2025-04-17        C027       3407.04
155  INV-2526-00076   2025-04-17        C027     143001.60
173  INV-2526-00087   2025-04-19        C023     238336.00
188  INV-2526-00094   2025-04-19        C019     -10393.60
257  INV-2526-00129   2025-04-26        C003       5544.00
258  INV-2526-00129   2025-04-26        C003      44604.00

In [85]:
sales_df[sales_df['payment_date'].isna()] [['invoice_no', 'invoice_date', 'customer_id', 'total_amount']]

          invoice_no invoice_date customer_id  total_amount
21    INV-2526-00011   2025-04-02        C017       4198.32
22    INV-2526-00011   2025-04-02        C017      38232.00
23    INV-2526-00011   2025-04-02        C017     172800.00
32    INV-2526-00018   2025-04-03        C010       2478.00
33    INV-2526-00018   2025-04-03        C010     190668.80
...              ...          ...         ...           ...
3628  INV-2526-01798   2026-03-31        C036      44604.00
3629  INV-2526-01799   2026-03-31        C009      97137.60
3630  INV-2526-01800   2026-03-31        C037      30680.00
3631  INV-2526-01800   2026-03-31        C037       8601.60
3632  INV-2526-01800   2026-03-31        C037       4950.40

[662 rows x 4 columns]

In [86]:
sales_df.duplicated().sum()

np.int64(53)

In [87]:
sales_df[sales_df.duplicated()]

,invoice_no,doc_type,invoice_date,customer_id,product_id,quantity,unit_price,discount_pct,taxable_value,cgst,sgst,igst,payment_date,total_amount
75,INV-2526-00040,Invoice,2025-04-09,C027,P04,4,9500,5.0,36100.0,0.00,0.00,6498.00,2025-05-26,42598.00
90,INV-2526-00046,Credit Note,2025-04-10,C024,P08,-19,150,0.0,-2850.0,-171.00,-171.00,-0.00,NaT,-3192.00
100,INV-2526-00050,Invoice,2025-04-10,C010,P08,13,150,0.0,1950.0,0.00,0.00,234.00,2025-06-06,2184.00
191,INV-2526-00095,Invoice,2025-04-20,C019,P12,3,27000,5.0,76950.0,0.00,0.00,21546.00,2025-05-25,98496.00
200,INV-2526-00100,Invoice,2025-04-21,C043,P02,11,700,0.0,7700.0,693.00,693.00,0.00,2025-05-06,9086.00
323,INV-2526-00163,Invoice,2025-05-05,C038,P01,2,42000,0.0,84000.0,7560.00,7560.00,0.00,2025-06-19,99120.00
439,INV-2526-00220,Invoice,2025-05-14,C037,P03,4,15000,0.0,60000.0,5400.00,5400.00,0.00,2025-06-02,70800.00
441,INV-2526-00221,Invoice,2025-05-15,C010,P07,18,320,2.0,5644.8,0.00,0.00,677.38,2025-07-14,6322.18
525,INV-2526-00263,Invoice,2025-05-23,C004,P10,15,240,0.0,3600.0,0.00,0.00,180.00,2025-07-07,3780.00
701,INV-2526-00348,Invoice,2025-06-08,C014,P04,3,9500,2.0,27930.0,2513.70,2513.70,0.00,2025-06-09,32957.40
711,INV-2526-00353,Invoice,2025-06-09,C020,P09,26,260,5.0,6422.0,0.00,0.00,770.64,NaT,7192.64
814,INV-2526-00404,Invoice,2025-06-20,C014,P01,1,42000,10.0,37800.0,3402.00,3402.00,0.00,2025-09-25,44604.00
913,INV-2526-00455,Invoice,2025-07-01,C036,P11,4,38000,0.0,152000.0,0.00,0.00,42560.00,2025-08-08,194560.00
929,INV-2526-00462,Invoice,2025-07-02,C017,P02,3,700,5.0,1995.0,179.55,179.55,0.00,2025-07-28,2354.10
935,INV-2526-00464,Invoice,2025-07-03,C029,P10,6,240,0.0,1440.0,36.00,36.00,0.00,2025-08-22,1512.00
1033,INV-2526-00511,Invoice,2025-07-13,C023,P04,2,9500,10.0,17100.0,0.00,0.00,3078.00,2025-08-17,20178.00
1133,INV-2526-00564,Invoice,2025-07-23,C007,P02,29,700,0.0,20300.0,0.00,0.00,3654.00,2025-08-04,23954.00
1197,INV-2526-00598,Invoice,2025-07-29,C010,P10,4,240,5.0,912.0,0.00,0.00,45.60,2025-10-07,957.60
1242,INV-2526-00621,Invoice,2025-08-02,C004,P05,4,6500,0.0,26000.0,0.00,0.00,4680.00,2025-09-09,30680.00
1281,INV-2526-00641,Invoice,2025-08-05,C026,P04,4,9500,0.0,38000.0,3420.00,3420.00,0.00,2025-09-01,44840.00
1325,INV-2526-00663,Invoice,2025-08-11,C014,P04,3,9500,0.0,28500.0,2565.00,2565.00,0.00,2025-09-07,33630.00
1334,INV-2526-00667,Invoice,2025-08-12,C014,P05,3,6500,0.0,19500.0,1755.00,1755.00,0.00,2025-08-31,23010.00
1447,INV-2526-00724,Credit Note,2025-08-22,C039,P06,-5,18000,0.0,-90000.0,-8100.00,-8100.00,-0.00,NaT,-106200.00
1495,INV-2526-00748,Invoice,2025-08-27,C023,P05,4,6500,0.0,26000.0,0.00,0.00,4680.00,2025-10-09,30680.00
1614,INV-2526-00804,Invoice,2025-09-06,C009,P11,4,38000,2.0,148960.0,20854.40,20854.40,0.00,2025-09-20,190668.80
1637,INV-2526-00814,Invoice,2025-09-09,C005,P12,5,27000,5.0,128250.0,0.00,0.00,35910.00,2025-10-13,164160.00
1709,INV-2526-00847,Invoice,2025-09-14,C024,P12,3,27000,0.0,81000.0,11340.00,11340.00,0.00,NaT,103680.00
1835,INV-2526-00909,Invoice,2025-09-27,C023,P10,23,240,2.0,5409.6,0.00,0.00,270.48,2025-10-27,5680.08
1859,INV-2526-00921,Invoice,2025-09-30,C027,P11,4,38000,10.0,136800.0,0.00,0.00,38304.00,2025-10-10,175104.00
1960,INV-2526-00967,Invoice,2025-10-09,C014,P05,4,6500,2.0,25480.0,2293.20,2293.20,0.00,2025-10-23,30066.40
2090,INV-2526-01035,Invoice,2025-10-23,C005,P03,5,15000,0.0,75000.0,0.00,0.00,13500.00,2025-11-17,88500.00
2130,INV-2526-01056,Invoice,2025-10-27,C001,P06,3,18000,0.0,54000.0,0.00,0.00,9720.00,2025-12-21,63720.00
2260,INV-2526-01120,Invoice,2025-11-11,C038,P04,3,9500,0.0,28500.0,2565.00,2565.00,0.00,2026-01-27,33630.00
2319,INV-2526-01152,Invoice,2025-11-18,C018,P06,5,18000,2.0,88200.0,0.00,0.00,15876.00,2026-01-01,104076.00
2331,INV-2526-01157,Invoice,2025-11-18,C004,P03,1,15000,0.0,15000.0,0.00,0.00,2700.00,2026-01-13,17700.00
2356,INV-2526-01170,Invoice,2025-11-22,C006,P08,29,150,10.0,3915.0,0.00,0.00,469.80,2026-02-19,4384.80
2409,INV-2526-01196,Invoice,2025-11-26,C020,P06,2,18000,2.0,35280.0,0.00,0.00,6350.40,2025-12-14,41630.40
2472,INV-2526-01230,Invoice,2025-12-04,C036,P06,3,18000,2.0,52920.0,0.00,0.00,9525.60,2026-01-26,62445.60
2623,INV-2526-01314,Invoice,2025-12-25,C010,P01,5,42000,0.0,210000.0,0.00,0.00,37800.00,2026-02-17,247800.00
2652,INV-2526-01329,Invoice,2025-12-28,C017,P04,2,9500,2.0,18620.0,1675.80,1675.80,0.00,2026-01-31,21971.60
2682,INV-2526-01344,Invoice,2025-12-30,C017,P01,3,42000,2.0,123480.0,11113.20,11113.20,0.00,2026-02-01,145706.40
2695,INV-2526-01349,Invoice,2025-12-31,C036,P06,2,18000,0.0,36000.0,0.00,0.00,6480.00,2026-01-31,42480.00
2748,INV-2526-01374,Invoice,2026-01-05,C005,P11,2,38000,0.0,76000.0,0.00,0.00,21280.00,2026-01-26,97280.00
2794,INV-2526-01398,Invoice,2026-01-10,C046,P09,26,260,5.0,6422.0,0.00,0.00,770.64,2026-01-19,7192.64
2819,INV-2526-01408,Invoice,2026-01-13,C036,P04,5,9500,5.0,45125.0,0.00,0.00,8122.50,2026-03-12,53247.50
2896,INV-2526-01442,Invoice,2026-01-19,C007,P02,8,700,0.0,5600.0,0.00,0.00,1008.00,2026-01-26,6608.00
2994,INV-2526-01490,Invoice,2026-02-01,C057,P01,3,42000,0.0,126000.0,0.00,0.00,22680.00,2026-03-26,148680.00
2996,INV-2526-01491,Invoice,2026-02-01,C048,P04,3,9500,10.0,25650.0,2308.50,2308.50,0.00,2026-03-10,30267.00
3218,INV-2526-01599,Invoice,2026-02-20,C020,P09,22,260,10.0,5148.0,0.00,0.00,617.76,NaT,5765.76
3338,INV-2526-01660,Invoice,2026-03-06,C001,P07,13,320,0.0,4160.0,0.00,0.00,499.20,NaT,4659.20
3386,INV-2526-01685,Invoice,2026-03-10,C014,P05,3,6500,2.0,19110.0,1719.90,1719.90,0.00,NaT,22549.80
3493,INV-2526-01735,Invoice,2026-03-20,C054,P04,2,9500,2.0,18620.0,0.00,0.00,3351.60,NaT,21971.60
3511,INV-2526-01742,Invoice,2026-03-21,C009,P02,15,700,2.0,10290.0,926.10,926.10,0.00,NaT,12142.20

In [88]:
sales_df = sales_df.drop_duplicates()

In [89]:
sales_df.duplicated().sum()

np.int64(0)

In [90]:
sales_df.shape

(3580, 14)

In [91]:
sales_df.isna().sum()

invoice_no         0
doc_type           0
invoice_date       0
customer_id        0
product_id         0
quantity           0
unit_price         0
discount_pct       0
taxable_value      0
cgst               0
sgst               0
igst               0
payment_date     653
total_amount       0
dtype: int64

In [92]:
sales_df['doc_type'].value_counts()

doc_type
Invoice        3509
Credit Note      71
Name: count, dtype: int64

In [93]:
sales_df.describe()

,invoice_date,quantity,unit_price,discount_pct,taxable_value,cgst,sgst,igst,payment_date,total_amount
count,3580,3580.000000,3580.000000,3580.000000,3580.000000,3580.000000,3580.000000,3580.000000,2927,3580.000000
mean,2025-09-29 22:01:44.581005,7.725978,13202.821229,2.752514,37398.054637,1493.850693,1493.850693,5098.812307,2025-10-15 09:26:15.538093,45484.568330
min,2025-04-01 00:00:00,-29.000000,150.000000,0.000000,-171000.000000,-23940.000000,-23940.000000,-38304.000000,2025-04-07 00:00:00,-218880.000000
25%,2025-06-30 00:00:00,2.000000,260.000000,0.000000,4200.000000,0.000000,0.000000,0.000000,2025-07-28 00:00:00,4691.960000
50%,2025-09-25 00:00:00,4.000000,6500.000000,0.000000,18000.000000,0.000000,0.000000,333.470000,2025-10-12 00:00:00,21240.000000
75%,2026-01-03 00:00:00,12.000000,27000.000000,5.000000,54000.000000,379.050000,379.050000,5832.000000,2026-01-05 00:00:00,67260.000000
max,2026-03-31 00:00:00,29.000000,42000.000000,10.000000,210000.000000,26600.000000,26600.000000,53200.000000,2026-03-31 00:00:00,247800.000000
std,NaN,8.445942,14672.552922,3.609723,49157.540526,4110.699954,4110.699954,10080.986595,NaN,60582.758809

In [94]:
sales_df[sales_df['total_amount'] < 0][['invoice_no', 'doc_type', 'quantity', 'taxable_value', 'cgst', 'sgst', 'igst', 'total_amount']]

,invoice_no,doc_type,quantity,taxable_value,cgst,sgst,igst,total_amount
89,INV-2526-00046,Credit Note,-19,-2850.0,-171.0,-171.0,-0.00,-3192.00
93,INV-2526-00048,Credit Note,-2,-12350.0,-0.0,-0.0,-2223.00,-14573.00
188,INV-2526-00094,Credit Note,-29,-9280.0,-0.0,-0.0,-1113.60,-10393.60
344,INV-2526-00172,Credit Note,-2,-12740.0,-1146.6,-1146.6,-0.00,-15033.20
371,INV-2526-00183,Credit Note,-11,-1650.0,-0.0,-0.0,-198.00,-1848.00
...,...,...,...,...,...,...,...,...
3344,INV-2526-01664,Credit Note,-4,-37240.0,-0.0,-0.0,-6703.20,-43943.20
3391,INV-2526-01687,Credit Note,-5,-32500.0,-2925.0,-2925.0,-0.00,-38350.00
3401,INV-2526-01691,Credit Note,-4,-38000.0,-0.0,-0.0,-6840.00,-44840.00
3481,INV-2526-01730,Credit Note,-2,-270.0,-0.0,-0.0,-32.40,-302.40
3562,INV-2526-01766,Credit Note,-15,-3822.0,-0.0,-0.0,-458.64,-4280.64

In [95]:
sales_df[['quantity', 'unit_price', 'discount_pct', 'taxable_value']].head(10)

   quantity  unit_price  discount_pct  taxable_value
0         1       42000           0.0        42000.0
1        21         240           0.0         5040.0
2        25         320           0.0         8000.0
3         4        9500           0.0        38000.0
4         5       18000           2.0        88200.0
5         2       18000           0.0        36000.0
6        23         700           0.0        16100.0
7        21         240           0.0         5040.0
8         1        9500           5.0         9025.0
9        25         700          10.0        15750.0

In [96]:
calculated_value = (
    sales_df['quantity'] * 
    sales_df['unit_price'] *
    (1 - sales_df['discount_pct'] / 100)  
)

(sales_df['taxable_value'] - calculated_value).abs().max()

np.float64(9.094947017729282e-13)

In [97]:
calculated_total = (
    sales_df['taxable_value']
    + sales_df['cgst']
    + sales_df['sgst']
    + sales_df['igst']
)

(sales_df['total_amount'] - calculated_total).abs().max()

np.float64(2.9103830456733704e-11)

In [98]:
customers_df = pd.read_csv("../data/raw/customers.csv")

In [99]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    60 non-null     str
 1   customer_name  60 non-null     str
 2   state          60 non-null     str
 3   segment        60 non-null     str
 4   credit_days    60 non-null     int64
 5   gstin          55 non-null     str
dtypes: int64(1), str(5)
memory usage: 2.9 KB

In [100]:
customers_df['state'].value_counts()

state
Karnataka         18
Delhi              7
Maharashtra        6
Tamil Nadu         5
Telangana          4
Kerala             3
KARNATAKA          3
gujarat            3
MH                 2
Gujarat            1
KA                 1
Maharastra         1
karnataka          1
Andhra Pradesh     1
KL                 1
AP                 1
New Delhi          1
GJ                 1
Name: count, dtype: int64

In [101]:
customers_df['state'] = customers_df['state'].replace({
    'KARNATAKA': 'Karnataka',
    'karnataka': 'Karnataka',
    'KA': 'Karnataka',
    'MH': 'Maharashtra',
    'Maharastra': 'Maharashtra',
    'gujarat': 'Gujarat',
    'GJ': 'Gujarat',
    'KL': 'Kerala',
    'AP': 'Andhra Pradesh',
    'New Delhi': 'Delhi'
})

In [102]:
customers_df['state'].value_counts()

state
Karnataka         20
Maharashtra        9
Delhi              8
Tamil Nadu         5
Gujarat            5
Telangana          4
Kerala             4
KARNATAKA          3
Andhra Pradesh     2
Name: count, dtype: int64

In [103]:
customers_df['state'] = customers_df['state'].str.strip().str.upper()

customers_df['state'] = customers_df['state'].replace({
    'KARNATAKA': 'Karnataka',
    'KA': 'Karnataka',
    'MAHARASHTRA': 'Maharashtra',
    'MAHARASTRA': 'Maharashtra',
    'MH': 'Maharashtra',
    'DELHI': 'Delhi',
    'NEW DELHI': 'Delhi',
    'TAMIL NADU': 'Tamil Nadu',
    'GUJARAT': 'Gujarat',
    'GJ': 'Gujarat',
    'TELANGANA': 'Telangana',
    'KERALA': 'Kerala',
    'KL': 'Kerala',
    'ANDHRA PRADESH': 'Andhra Pradesh',
    'AP': 'Andhra Pradesh'
})

In [104]:
customers_df['state'].value_counts()

state
Karnataka         23
Maharashtra        9
Delhi              8
Tamil Nadu         5
Gujarat            5
Telangana          4
Kerala             4
Andhra Pradesh     2
Name: count, dtype: int64

In [105]:
customers_df[customers_df['gstin'].isna()]

,customer_id,customer_name,state,segment,credit_days,gstin
4,C005,Trident Traders,Telangana,Retail,15,NaN
25,C026,Bharat Retail,Karnataka,Retail,15,NaN
38,C039,Jai Ganesh Distributors,Karnataka,Wholesale,30,NaN
53,C054,Unity Traders,Telangana,Wholesale,30,NaN
58,C059,Trident Enterprises,Maharashtra,Wholesale,30,NaN

In [106]:
customers_df['gstin'] = customers_df['gstin'].fillna('Not Available')

In [107]:
customers_df['gstin'].isna().sum()

np.int64(0)

In [108]:
customers_df[customers_df['gstin'] == 'Not Available']

,customer_id,customer_name,state,segment,credit_days,gstin
4,C005,Trident Traders,Telangana,Retail,15,Not Available
25,C026,Bharat Retail,Karnataka,Retail,15,Not Available
38,C039,Jai Ganesh Distributors,Karnataka,Wholesale,30,Not Available
53,C054,Unity Traders,Telangana,Wholesale,30,Not Available
58,C059,Trident Enterprises,Maharashtra,Wholesale,30,Not Available

In [109]:
customers_df['gstin'].value_counts()

gstin
Not Available      5
07CVXFX1543A1Z7    1
27IRKJX0773G1Z0    1
33YYGAD0881T1Z1    1
24JPSWB1239U1Z3    1
33ARZDH5967P1Z4    1
33FWUAS0781L1Z1    1
29OYCKZ3145R1Z3    1
29YNHYY4055D1Z6    1
27VCSDT4091P1Z1    1
29YTULM6780R1Z1    1
27HVGUM2357P1Z9    1
32WTPHK1394C1Z6    1
29ZWHLN2229T1Z8    1
29VYCWB4531E1Z8    1
29IIYDX9511H1Z5    1
29DLDOA7011V1Z0    1
07LPNRU3839N1Z7    1
33WUWNB4182F1Z2    1
24QOYKH0039N1Z8    1
07CCVCB4960V1Z8    1
27UXGZI8576Q1Z6    1
24UTDVN3598V1Z4    1
29UKRQG2014M1Z1    1
29KPGIJ5373L1Z3    1
07ILNYW4628O1Z5    1
27TQBHE7025S1Z5    1
29WXDYP6067P1Z0    1
33NYSDY9184P1Z4    1
29UZUYY0275B1Z0    1
07NQEED5054M1Z6    1
27NSTXU5425D1Z9    1
29VDUDS0467K1Z9    1
29UFRSI7887Q1Z2    1
36UJNII1910Y1Z5    1
29LTJDS1599J1Z7    1
29PMDJQ9078Y1Z4    1
37OACLS8429L1Z3    1
32LAHNX7751K1Z9    1
07BWRHU8016Z1Z0    1
29RDQQC6880G1Z2    1
37LDWUV1092R1Z9    1
24AAAEB8698Z1Z2    1
07HWGBR8991U1Z8    1
27SVVLB4211S1Z5    1
29OTOQC8418T1Z0    1
29FAHCS5976N1Z0    1
32BQABF8474E1Z3    1
27CUEJZ5457G1Z6    1
29WOLDG9534P1Z5    1
29SGQLY1145R1Z4    1
29LUPKQ9414V1Z2    1
32YPPIX0244M1Z1    1
24FCOJO5756P1Z6    1
07QIGUI5145Q1Z5    1
36TNGUG3583M1Z0    1
Name: count, dtype: int64

In [110]:
customers_df.isna().sum()

customer_id      0
customer_name    0
state            0
segment          0
credit_days      0
gstin            0
dtype: int64

In [111]:
cleaning_log = {
    "State names": "Standardised inconsistent state names",
    "Duplicate rows": "Removed duplicate rows from sales data",
    "Missing GSTIN": "Replaced missing GSTIN values with 'Not Available'",
    "Dates": "Standardised invoice and payment dates"
}

cleaning_log

{'State names': 'Standardised inconsistent state names',
 'Duplicate rows': 'Removed duplicate rows from sales data',
 'Missing GSTIN': "Replaced missing GSTIN values with 'Not Available'",
 'Dates': 'Standardised invoice and payment dates'}

In [112]:
print(sales_df.shape)
print(customers_df.shape)

(3580, 14)
(60, 6)

In [113]:
import os

os.listdir("../data/raw")

['customers.csv', 'products.csv', 'purchases.csv', 'sales_invoices.csv']

In [114]:
products_df = pd.read_csv("../data/raw/products.csv")
purchases_df = pd.read_csv("../data/raw/purchases.csv")

In [115]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     12 non-null     str
 1   product_name   12 non-null     str
 2   category       12 non-null     str
 3   hsn_code       12 non-null     int64
 4   gst_rate       12 non-null     int64
 5   selling_price  12 non-null     int64
 6   cost_price     12 non-null     int64
dtypes: int64(4), str(3)
memory usage: 804.0 bytes

In [116]:
purchases_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   purchase_id     500 non-null    str
 1   purchase_date   500 non-null    str
 2   supplier_id     500 non-null    str
 3   supplier_name   500 non-null    str
 4   supplier_gstin  449 non-null    str
 5   category        500 non-null    str
 6   taxable_value   500 non-null    float64
 7   gst_amount      500 non-null    float64
 8   itc_claimed     500 non-null    str
dtypes: float64(2), str(7)
memory usage: 35.3 KB

In [117]:

print("SALES COLUMNS:")
print(sales_df.columns.tolist())

print("\nCUSTOMERS COLUMNS:")
print(df.columns.tolist())

print("\nPRODUCTS COLUMNS:")
print(products_df.columns.tolist())

print("\nPURCHASES COLUMNS:")
print(purchases_df.columns.tolist())

SALES COLUMNS:
['invoice_no', 'doc_type', 'invoice_date', 'customer_id', 'product_id', 'quantity', 'unit_price', 'discount_pct', 'taxable_value', 'cgst', 'sgst', 'igst', 'payment_date', 'total_amount']

CUSTOMERS COLUMNS:
['customer_id', 'customer_name', 'state', 'segment', 'credit_days', 'gstin']

PRODUCTS COLUMNS:
['product_id', 'product_name', 'category', 'hsn_code', 'gst_rate', 'selling_price', 'cost_price']

PURCHASES COLUMNS:
['purchase_id', 'purchase_date', 'supplier_id', 'supplier_name', 'supplier_gstin', 'category', 'taxable_value', 'gst_amount', 'itc_claimed']

In [118]:
for col in sales_df.columns:
    print(col)

invoice_no
doc_type
invoice_date
customer_id
product_id
quantity
unit_price
discount_pct
taxable_value
cgst
sgst
igst
payment_date
total_amount

In [119]:

%pip install mysql-connector-python sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\Users\Asus\anaconda3\envs\gst_analysis\Lib\site-packages (26.7.0)
Requirement already satisfied: sqlalchemy in c:\Users\Asus\anaconda3\envs\gst_analysis\Lib\site-packages (2.1.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\Asus\anaconda3\envs\gst_analysis\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [120]:
import mysql.connector
from sqlalchemy import create_engine

print("MySQL connector imported successfully!")

MySQL connector imported successfully!

In [121]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="desuvineel@02",
    database="gst_analysis"
)

if conn.is_connected():
    print("Connected to MySQL successfully!")

Connected to MySQL successfully!

In [122]:
%whos

Variable           Type               Data/Info
-----------------------------------------------
calculated_total   Series             Shape: (3580,)
calculated_value   Series             Shape: (3580,)
cleaning_log       dict               n=4
col                str                total_amount
conn               MySQLConnection    <mysql.connector.connecti<...>ct at 0x000002BAB9FA0C20>
create_engine      function           <function create_engine at 0x000002BABA724360>
customers_df       DataFrame          Shape: (60, 6)
dataframe          DataFrame          Shape: (60, 6)
df                 DataFrame          Shape: (60, 6)
engine             Engine             Engine(mysql+mysqlconnect<...>alhost:3306/gst_analysis)
mysql              module             <module 'mysql' from 'c:\<...>ges\\mysql\\__init__.py'>
os                 module             <module 'os' (frozen)>
password           str                desuvineel%4002
pd                 module             <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
products_df        DataFrame          Shape: (12, 7)
purchases_df       DataFrame          Shape: (500, 9)
quote_plus         function           <function quote_plus at 0x000002BAA4EB7B00>
sales_df           DataFrame          Shape: (3580, 14)
table_name         str                customers
tables             dict               n=4

In [123]:
print("Customers:", customers_df.shape)
print("Products:", products_df.shape)
print("Purchases:", purchases_df.shape)
print("Sales:", sales_df.shape)

Customers: (60, 6)
Products: (12, 7)
Purchases: (500, 9)
Sales: (3580, 14)

In [124]:
print("CUSTOMERS:", customers_df.columns.tolist())
print("PRODUCTS:", products_df.columns.tolist())
print("PURCHASES:", purchases_df.columns.tolist())
print("SALES:", sales_df.columns.tolist())

CUSTOMERS: ['customer_id', 'customer_name', 'state', 'segment', 'credit_days', 'gstin']
PRODUCTS: ['product_id', 'product_name', 'category', 'hsn_code', 'gst_rate', 'selling_price', 'cost_price']
PURCHASES: ['purchase_id', 'purchase_date', 'supplier_id', 'supplier_name', 'supplier_gstin', 'category', 'taxable_value', 'gst_amount', 'itc_claimed']
SALES: ['invoice_no', 'doc_type', 'invoice_date', 'customer_id', 'product_id', 'quantity', 'unit_price', 'discount_pct', 'taxable_value', 'cgst', 'sgst', 'igst', 'payment_date', 'total_amount']

In [125]:
tables = {
    "customers": customers_df,
    "products": products_df,
    "purchases": purchases_df,
    "sales": sales_df
}

for table_name, dataframe in tables.items():
    print(table_name, dataframe.shape)

customers (60, 6)
products (12, 7)
purchases (500, 9)
sales (3580, 14)

In [126]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("desuvineel@02")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost:3306/gst_analysis"
)

In [127]:
print(engine)

Engine(mysql+mysqlconnector://root:***@localhost:3306/gst_analysis)

In [128]:
print(hasattr(customers_df, "to_sql"))

True

In [130]:
purchases_df.to_sql(
    name="purchases",
    con=engine,
    if_exists="append",
    index=False
)

DatabaseError: Execution failed on sql 'INSERT INTO purchases (purchase_id, purchase_date, supplier_id, supplier_name, supplier_gstin, category, taxable_value, gst_amount, itc_claimed) VALUES (:purchase_id, :purchase_date, :supplier_id, :supplier_name, :supplier_gstin, :category, :taxable_value, :gst_amount, :itc_claimed)': (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'PUR-0468' for key 'purchases.PRIMARY'
[SQL: INSERT INTO purchases (purchase_id, purchase_date, supplier_id, supplier_name, supplier_gstin, category, taxable_value, gst_amount, itc_claimed) VALUES (%(purchase_id)s, %(purchase_date)s, %(supplier_id)s, %(supplier_name)s, %(supplier_gstin)s, %(category)s, %(taxable_value)s, %(gst_amount)s, %(itc_claimed)s)]
[parameters: [{'purchase_id': 'PUR-0468', 'purchase_date': '2025-04-02', 'supplier_id': 'S04', 'supplier_name': 'Supplier D Pvt Ltd', 'supplier_gstin': '24SGVRY6057U1Z3', 'category': 'Inventory', 'taxable_value': 384525.71, 'gst_amount': 69214.63, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0385', 'purchase_date': '2025-04-04', 'supplier_id': 'S09', 'supplier_name': 'Supplier I Pvt Ltd', 'supplier_gstin': '29SBCFB5806L1Z8', 'category': 'Freight', 'taxable_value': 2150.3, 'gst_amount': 107.52, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0093', 'purchase_date': '2025-04-04', 'supplier_id': 'S10', 'supplier_name': 'Supplier J Pvt Ltd', 'supplier_gstin': '32MRXDI2160K1Z1', 'category': 'Vehicle Expenses', 'taxable_value': 15937.59, 'gst_amount': 4462.53, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0423', 'purchase_date': '2025-04-04', 'supplier_id': 'S07', 'supplier_name': 'Supplier G Pvt Ltd', 'supplier_gstin': '32FGWPZ4396W1Z0', 'category': 'Vehicle Expenses', 'taxable_value': 5852.27, 'gst_amount': 1638.64, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0351', 'purchase_date': '2025-04-05', 'supplier_id': 'S07', 'supplier_name': 'Supplier G Pvt Ltd', 'supplier_gstin': '32FGWPZ4396W1Z0', 'category': 'Inventory', 'taxable_value': 281896.2, 'gst_amount': 33827.54, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0480', 'purchase_date': '2025-04-06', 'supplier_id': 'S01', 'supplier_name': 'Supplier A Pvt Ltd', 'supplier_gstin': '07EDBXA8569U1Z1', 'category': 'Inventory', 'taxable_value': 316432.11, 'gst_amount': 56957.78, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0035', 'purchase_date': '2025-04-07', 'supplier_id': 'S23', 'supplier_name': 'Supplier W Pvt Ltd', 'supplier_gstin': '33PUULX9381C1Z5', 'category': 'Inventory', 'taxable_value': 172249.22, 'gst_amount': 48229.78, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0203', 'purchase_date': '2025-04-07', 'supplier_id': 'S16', 'supplier_name': 'Supplier P Pvt Ltd', 'supplier_gstin': '07BIQRI8877Z1Z7', 'category': 'Office Supplies', 'taxable_value': 6266.65, 'gst_amount': 1128.0, 'itc_claimed': 'Y'}  ... displaying 10 of 500 total bound parameter sets ...  {'purchase_id': 'PUR-0173', 'purchase_date': '2026-03-30', 'supplier_id': 'S12', 'supplier_name': 'Supplier L Pvt Ltd', 'supplier_gstin': '27CHGIW9619W1Z0', 'category': 'Inventory', 'taxable_value': 119322.42, 'gst_amount': 33410.28, 'itc_claimed': 'Y'}, {'purchase_id': 'PUR-0214', 'purchase_date': '2026-03-31', 'supplier_id': 'S12', 'supplier_name': 'Supplier L Pvt Ltd', 'supplier_gstin': '27CHGIW9619W1Z0', 'category': 'Inventory', 'taxable_value': 41499.9, 'gst_amount': 4979.99, 'itc_claimed': 'Y'}]]
(Background on this error at: https://sqlalche.me/e/21/gkpj)

In [131]:
sales_df.to_sql(
    name="sales",
    con=engine,
    if_exists="append",
    index=False
)

-1

In [133]:
print([name for name in ["df", "sales_df", "products_df", "purchases_df"]
       if name in globals()])

['df', 'sales_df', 'products_df', 'purchases_df']

In [134]:
import os

clean_folder = "../data/clean"
os.makedirs(clean_folder, exist_ok=True)

customers_df.to_csv(
    os.path.join(clean_folder, "customers_clean.csv"),
    index=False
)

sales_df.to_csv(
    os.path.join(clean_folder, "sales_clean.csv"),
    index=False
)

products_df.to_csv(
    os.path.join(clean_folder, "products_clean.csv"),
    index=False
)

purchases_df.to_csv(
    os.path.join(clean_folder, "purchases_clean.csv"),
    index=False
)

print("Files saved successfully!")
print(os.listdir(clean_folder))

Files saved successfully!
['customers_clean.csv', 'products_clean.csv', 'purchases_clean.csv', 'sales_clean.csv']

In [135]:
for name, data in {
    "Customers": df,
    "Sales": sales_df,
    "Products": products_df,
    "Purchases": purchases_df
}.items():
    print(f"\n{name}:")
    print(data.columns.tolist())

Customers:
['customer_id', 'customer_name', 'state', 'segment', 'credit_days', 'gstin']

Sales:
['invoice_no', 'doc_type', 'invoice_date', 'customer_id', 'product_id', 'quantity', 'unit_price', 'discount_pct', 'taxable_value', 'cgst', 'sgst', 'igst', 'payment_date', 'total_amount']

Products:
['product_id', 'product_name', 'category', 'hsn_code', 'gst_rate', 'selling_price', 'cost_price']

Purchases:
['purchase_id', 'purchase_date', 'supplier_id', 'supplier_name', 'supplier_gstin', 'category', 'taxable_value', 'gst_amount', 'itc_claimed']

In [136]:
print("Sales data:")
display(sales_df.head())

print("\nSales data types:")
print(sales_df.dtypes)

print("\nPurchase data:")
display(purchases_df.head())

print("\nPurchase data types:")
print(purchases_df.dtypes)

Sales data:

,invoice_no,doc_type,invoice_date,customer_id,product_id,quantity,unit_price,discount_pct,taxable_value,cgst,sgst,igst,payment_date,total_amount
0,INV-2526-00001,Invoice,2025-04-01,C038,P01,1,42000,0.0,42000.0,3780.0,3780.0,0.0,2025-06-13,49560.0
1,INV-2526-00001,Invoice,2025-04-01,C038,P10,21,240,0.0,5040.0,126.0,126.0,0.0,2025-06-13,5292.0
2,INV-2526-00001,Invoice,2025-04-01,C038,P07,25,320,0.0,8000.0,480.0,480.0,0.0,2025-06-13,8960.0
3,INV-2526-00002,Invoice,2025-04-01,C010,P04,4,9500,0.0,38000.0,0.0,0.0,6840.0,2025-05-23,44840.0
4,INV-2526-00002,Invoice,2025-04-01,C010,P06,5,18000,2.0,88200.0,0.0,0.0,15876.0,2025-05-23,104076.0

Sales data types:
invoice_no                  str
doc_type                    str
invoice_date     datetime64[us]
customer_id                 str
product_id                  str
quantity                  int64
unit_price                int64
discount_pct            float64
taxable_value           float64
cgst                    float64
sgst                    float64
igst                    float64
payment_date     datetime64[us]
total_amount            float64
dtype: object

Purchase data:

,purchase_id,purchase_date,supplier_id,supplier_name,supplier_gstin,category,taxable_value,gst_amount,itc_claimed
0,PUR-0468,2025-04-02,S04,Supplier D Pvt Ltd,24SGVRY6057U1Z3,Inventory,384525.71,69214.63,Y
1,PUR-0385,2025-04-04,S09,Supplier I Pvt Ltd,29SBCFB5806L1Z8,Freight,2150.30,107.52,Y
2,PUR-0093,2025-04-04,S10,Supplier J Pvt Ltd,32MRXDI2160K1Z1,Vehicle Expenses,15937.59,4462.53,Y
3,PUR-0423,2025-04-04,S07,Supplier G Pvt Ltd,32FGWPZ4396W1Z0,Vehicle Expenses,5852.27,1638.64,Y
4,PUR-0351,2025-04-05,S07,Supplier G Pvt Ltd,32FGWPZ4396W1Z0,Inventory,281896.20,33827.54,Y

Purchase data types:
purchase_id           str
purchase_date         str
supplier_id           str
supplier_name         str
supplier_gstin        str
category              str
taxable_value     float64
gst_amount        float64
itc_claimed           str
dtype: object

In [137]:
# Sales GST summary
sales_gst = sales_df[["cgst", "sgst", "igst"]].sum()

output_gst = sales_gst.sum()

# Purchase ITC summary
eligible_purchases = purchases_df[
    purchases_df["itc_claimed"].astype(str).str.upper().str.strip() == "Y"
]

eligible_itc = eligible_purchases["gst_amount"].sum()

# Net GST payable
net_payable = output_gst - eligible_itc

print("OUTPUT GST SUMMARY")
print(sales_gst)
print("Total output GST:", round(output_gst, 2))

print("\nINPUT TAX CREDIT")
print("Eligible purchase records:", len(eligible_purchases))
print("Eligible ITC:", round(eligible_itc, 2))

print("\nNET GST PAYABLE")
print(round(net_payable, 2))

OUTPUT GST SUMMARY
cgst     5347985.48
sgst     5347985.48
igst    18253748.06
dtype: float64
Total output GST: 28949719.02

INPUT TAX CREDIT
Eligible purchase records: 474
Eligible ITC: 11051294.04

NET GST PAYABLE
17898424.98

In [138]:
sales_df["expected_total"] = (
    sales_df["taxable_value"]
    + sales_df["cgst"]
    + sales_df["sgst"]
    + sales_df["igst"]
)

sales_df["total_difference"] = (
    sales_df["total_amount"] - sales_df["expected_total"]
).round(2)

tax_mismatches = sales_df[
    sales_df["total_difference"].abs() > 0.01
]

print("Total sales rows:", len(sales_df))
print("Rows with total amount mismatches:", len(tax_mismatches))
print("\nSample mismatches:")
display(
    tax_mismatches[
        ["invoice_no", "taxable_value", "cgst", "sgst",
         "igst", "total_amount", "expected_total",
         "total_difference"]
    ].head(10)
)

Total sales rows: 3580
Rows with total amount mismatches: 0

Sample mismatches:

Empty DataFrame
Columns: [invoice_no, taxable_value, cgst, sgst, igst, total_amount, expected_total, total_difference]
Index: []

In [139]:
print("Purchase rows:", len(purchases_df))

print("\nITC claimed values:")
print(purchases_df["itc_claimed"].value_counts(dropna=False))

print("\nGST amount total:",
      round(purchases_df["gst_amount"].sum(), 2))

print("\nITC claimed amount:",
      round(eligible_purchases["gst_amount"].sum(), 2))

print("\nITC not claimed amount:",
      round(
          purchases_df.loc[
              purchases_df["itc_claimed"].astype(str).str.upper().str.strip() != "Y",
              "gst_amount"
          ].sum(),
          2
      ))

Purchase rows: 500

ITC claimed values:
itc_claimed
Y    474
N     26
Name: count, dtype: int64

GST amount total: 11481741.98

ITC claimed amount: 11051294.04

ITC not claimed amount: 430447.94

In [140]:
net_payable = output_gst - eligible_itc

print("Total Output GST:", round(output_gst, 2))
print("Eligible ITC marked Y:", round(eligible_itc, 2))
print("Preliminary Net GST Payable:", round(net_payable, 2))

Total Output GST: 28949719.02
Eligible ITC marked Y: 11051294.04
Preliminary Net GST Payable: 17898424.98

In [141]:
import pandas as pd
import os

# Create output folder
output_folder = "../outputs"
os.makedirs(output_folder, exist_ok=True)

file_path = os.path.join(
    output_folder,
    "GST_Reconciliation_Summary.xlsx"
)

# 1. GST Summary
gst_summary = pd.DataFrame({
    "Metric": [
        "Total Taxable Sales",
        "CGST Collected",
        "SGST Collected",
        "IGST Collected",
        "Total Output GST"
    ],
    "Amount": [
        sales_df["taxable_value"].sum(),
        sales_df["cgst"].sum(),
        sales_df["sgst"].sum(),
        sales_df["igst"].sum(),
        output_gst
    ]
})

# 2. ITC Summary
itc_summary = pd.DataFrame({
    "Metric": [
        "Total Purchase GST",
        "ITC Marked Y",
        "ITC Marked N",
        "Eligible Purchase Records",
        "Non-claimed Purchase Records"
    ],
    "Value": [
        purchases_df["gst_amount"].sum(),
        eligible_itc,
        purchases_df.loc[
            purchases_df["itc_claimed"].astype(str).str.upper().str.strip() != "Y",
            "gst_amount"
        ].sum(),
        len(eligible_purchases),
        len(purchases_df) - len(eligible_purchases)
    ]
})

# 3. Net Payable
net_summary = pd.DataFrame({
    "Metric": [
        "Total Output GST",
        "ITC Marked Y",
        "Preliminary Net GST Payable"
    ],
    "Amount": [
        output_gst,
        eligible_itc,
        net_payable
    ]
})

# 4. Tax Errors
tax_errors = tax_mismatches[
    [
        "invoice_no", "taxable_value", "cgst", "sgst",
        "igst", "total_amount", "expected_total",
        "total_difference"
    ]
].copy()

with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
    gst_summary.to_excel(writer, sheet_name="GST Summary", index=False)
    itc_summary.to_excel(writer, sheet_name="ITC Summary", index=False)
    net_summary.to_excel(writer, sheet_name="Net Payable", index=False)
    tax_errors.to_excel(writer, sheet_name="Tax Errors", index=False)

print("Excel workbook created successfully!")
print("Saved at:", os.path.abspath(file_path))

Excel workbook created successfully!
Saved at: c:\Users\Asus\OneDrive\Desktop\Mini Project\GST Analysis\outputs\GST_Reconciliation_Summary.xlsx